name: Daily Stock Predictions

on:
  schedule:
    # Run at 21:00 UTC (5:00 PM ET standard time, 4:00 PM ET during DST)
    - cron: "0 21 * * 1-5"
  workflow_dispatch:  # allows manual trigger

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run live prediction
        run: python live_prediction.py

      - name: Commit & push predictions log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add predictions_log.csv
          git commit -m "Update predictions log for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
